Blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('resume.urls',namespace='resume')),
    path('blog/', include('myblog.urls', namespace='blog')),
]

myblog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'my_blog'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('signin/', views.signin, name='signin'),
    path('signout/',auth_views.logout,{"template_name":"signout.html"},name='signout'),
    path(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    path(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    path(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
]

resume/urls.py
from django.urls import path
from . import views

app_name = 'resume'

urlpatterns = [
    path('',views.index,name='index'),
]

myblog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
import markdown
from django.utils.html import strip_tags
# Create your models here.

# 分类
class Category(models.Model):
    name=models.CharField(max_length=100)

    def __str__(self):
        return self.name


#标签
class Tag(models.Model):
    name=models.CharField(max_length=100)

    def __str__(self):
        return self.name


#博客
class Post(models.Model):
    #文章标题
    title=models.CharField(max_length=100,verbose_name="标题")
    #文章内容
    body=models.TextField(verbose_name="博客内容")
    #发表时间
    created_time=models.DateTimeField(default=timezone.now,verbose_name="发表时间")
    #修改时间
    modified_time=models.DateTimeField(verbose_name="最后修改时间")
    #摘要
    excerpt=models.CharField(max_length=200,blank=True,verbose_name="摘要")
    #分类
    category=models.ForeignKey(Category,on_delete=models.CASCADE,verbose_name="分类")
    #标签
    tages=models.ManyToManyField(Tag,blank=True,verbose_name="标签")
    #作者
    author=models.ForeignKey(User,related_name="blog_posts",on_delete=models.CASCADE,verbose_name="作者")
    # 阅读量
    view_times = models.PositiveIntegerField(default=0)

    class Meta:
        ordering=("-created_time",)

    def increase_view_times(self):
        self.views += 1
        self.save(update_fields=['view_times'])

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.excerpt:
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.excerpt = strip_tags(md.convert(self.body))[:54]
        super(Post, self).save(*args, **kwargs)

resume/models.py
from django.db import models

# Create your models here.

myblog/forms.py
from django import forms
from .models import Category,Tag,Post


# class CategoryForm(forms.ModelForm):
#     class Meta:
#         model = Category
#         fields = ('cotegory',)

class SigninForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField(widget=forms.PasswordInput)

class CategoryForm(forms.ModelForm):
    class Meta:
        model=Category
        fields=['name',]

class TagForm(forms.ModelForm):
    class Meta:
        model=Tag
        fields=['name',]

class PostForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=['title','body']

myblog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Post, Tag
import markdown
from .forms import SigninForm
from django.contrib.auth import authenticate,login
from django.http import HttpResponse
# Create your views here.
def blog(request):
    category_list = Category.objects.all()
    tag_list = Tag.objects.all()
    post_list = Post.objects.all()
    return render(request, 'blog/index.html',
                  context={'post_list': post_list, 'tag_list': tag_list, 'category_list': category_list})


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.body = markdown.markdown(post.body,
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc',
                                  ])
    return render(request, 'blog/detail.html', context={'post': post})


def archives(request, year, month):
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})


def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})

def signin(request):
    if request.method == "POST":
        signin_form=SigninForm(request._post)
        if signin_form.is_valid():
            cd=signin_form.cleaned_data
            user=authenticate(username=cd['username'],password=cd['password'])
            if user:
                login(request,user)
                return HttpResponse("Welcome.")
            else:
                return HttpResponse("Sorry.")
        else:
            return HttpResponse("Invalid signin")
    if request.method == "GET":
        signin_form=SigninForm()
        return render(request, 'signin.html',context={'form':signin_form})

resume/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'resume.html')

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog - AlanMaxwell</title>

    <!-- Bootstrap core CSS -->
{#    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">#}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/highlights/github.css' %}">
    <style>
        body {
            padding-top: 50px;
        }
    </style>
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="col-md-8">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'resume:index' %}">AlanMaxwell</a>
            </div>
        </div>

        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'my_blog:blog' %}">首页</a></li>
                <li><a href="#about">分类</a></li>
                <li><a href="#contact">归档</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">个人<strong class="caret"></strong></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#">Info</a>
                        </li>
                        <li class="divider">
                        </li>
                        <li>
                            <a href="{% url 'my_blog:signin' %}">Sign In</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock %}
            </main>
            <aside class="col-md-4">
                {% block sidebar %}
                {% endblock %}
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">
                    Django2.0 & Bootstrap
                    <br>
                    <small>© Copyright AlanMaxwell.</small>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</body>
</html>

templates/blog/admin.html
{% extends 'base.html' %}
{% load blog_tags %}
{% block main %}

{% endblock %}

templates/blog/detail.html
{% extends 'base.html' %}
{% load blog_tags %}
{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="#">{{ post.title }}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category }}</a></span>
                <span class="post-date"><a href="#"><time
                        class="entry-date">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                {#                            <span class="comments-link"><a href="#">Comment</a></span>#}
                <span class="views-count"><a href="#">{{ post.view_times }}</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
        </div>
    </article>
{% endblock %}

{% block sidebar %}
    <div class="widget widget-recent-posts">
        <h3 class="widget-title">最新文章</h3>
        {% get_recent_posts as recent_post_list %}
        <ul>
            {% for post in recent_post_list %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
            {% empty %}
                暂无文章！
            {% endfor %}
        </ul>
    </div>
    <div class="widget widget-archives">
        <h3 class="widget-title">归档</h3>
        {% archives as date_list %}
        <ul>
            {% for date in date_list %}
                <li>
                    <a href="#">{{ date.year }} 年 {{ date.month }} 月</a>
                </li>
            {% empty %}
                暂无归档！
            {% endfor %}
        </ul>
    </div>

    <div class="widget widget-category">
        <h3 class="widget-title">分类</h3>
        {% get_categories as category_list %}
        <ul>
            {% for category in category_list %}
                <li>
                    <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span class="post-count"></span></a>
                </li>
            {% empty %}
                暂无分类！
            {% endfor %}
        </ul>
    </div>

    <div class="widget widget-tag-cloud">
        <h3 class="widget-title">标签云</h3>
        <ul>

        </ul>
    </div>
    <div class="rss">
        <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
    </div>
{% endblock %}

templates/blog/index.html
{% extends 'base.html' %}
{% load blog_tags %}
{% block main %}
    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
                        <header class="entry-header">
                            <h1 class="entry-title">
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </h1>
                            <div class="entry-meta">
                                <span class="post-category"><a href="#">{{ post.category }}</a></span>
                                <span class="post-date"><a href="#"><time
                                        class="entry-date">{{ post.created_time }}</time></a></span>
                                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                                {#                            <span class="comments-link"><a href="#">Comment</a></span>#}
                                <span class="views-count"><a href="#">{{ post.view_times }}</a></span>
                            </div>
                        </header>
                        <div class="entry-content clearfix">
                            <p>{{ post.excerpt }}...</p>
                            <div class="read-more cl-effect-14">
                                <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span
                                        class="meta-nav">→</span></a>
                            </div>
                        </div>
                    </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
                {% endfor %}
{% endblock %}

{% block sidebar %}
    <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
        {% get_recent_posts as recent_post_list %}
        <ul>
            {% for post in recent_post_list %}
                <li>
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </li>
            {% empty %}
                暂无文章！
            {% endfor %}
        </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }}
                                月</a>
                        </li>
                        {% empty %}
                            暂无归档！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                            <li>
                                <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span
                                        class="post-count"></span></a>
                            </li>
                        {% empty %}
                            暂无分类！
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% for tag in tag_list %}
                            <li>
                                <a href="#">{{ tag.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
{% endblock %}

templates/signin.html
{% extends 'base.html' %}
{% load blog_tags %}
{% block main %}
    <div class="row text-center vertical-middle-sm">
    <h1>Sign In</h1>
    <p>Input your name and password</p>
    <form class="form-horizontal" action="." method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Signin">
    </form>
    </div>
{% endblock %}

templates/signout.html
{% extends 'base.html' %}
{% load blog_tags %}
{% block main %}
    <div class="row text-center vertical-middle-sm">
    <h1>Sign Out</h1>
    <h3>You have signed out.</h3>
    <h3>Thank you!</h3>
    </div>
{% endblock %}